### ISSUE TITLE
Issue testing Helpers after upgrading to Rails 6.1

### ISSUE THREAD

**Issue by clinejj** [metaskills/minitest-spec-rails#106]
Hello, I'm seeing an issue where the helper methods are returning undefined after upgrading to Rails 6.1 (there was no issue with Rails 6.0). I'm not seeing issues with other spec style tests for other entities (eg models).

Helper file (app/helpers/purchase_order_helper.rb):
```ruby
module PurchaseOrderHelper
  def po_form_url(purchase_order, current_organization)
    return purchase_orders_path if purchase_order.new_record?

    if current_organization == purchase_order.buyer
      purchase_order_path(purchase_order)
    else
      selling_purchase_order_path(purchase_order)
    end
  end

  def po_table_view_class(purchase_orders, fixed_height)
    classes = 'table-inner-wrapper'
    if fixed_height
      classes += '-fh '
      classes += 'max-' if purchase_orders.present?
      classes += 'h-60'
    elsif purchase_orders.blank?
      classes += ' min-h-60'
    end
    classes
  end
end
```

Test file (/test/helpers/purchase_order_helper_test.rb)
```ruby
require 'test_helper'

describe PurchaseOrderHelper do
  describe '#po_form_url' do
    it 'should return the expected paths' do
      assert_equal purchase_orders_path,
                   PurchaseOrderHelper.po_form_url(PurchaseOrder.new, organizations(:brewco))
      assert_equal purchase_order_path(purchase_orders(:draft).visible_id),
                   po_form_url(purchase_orders(:draft), organizations(:brewco))
      assert_equal selling_purchase_order_path(purchase_orders(:draft).visible_id),
                   po_form_url(purchase_orders(:draft), organizations(:bluth))
    end
  end

  describe '#po_table_view_class' do
    it 'should return the expected classes' do
      assert_equal 'table-inner-wrapper-fh h-60', po_table_view_class([], true)
      assert_equal 'table-inner-wrapper min-h-60', po_table_view_class([], false)
      assert_equal 'table-inner-wrapper-fh max-h-60', po_table_view_class([1], true)
      assert_equal 'table-inner-wrapper', po_table_view_class([1], false)
    end
  end
end
```

This test previously worked without issues in Rails 6.0, but returns the following errors after updating to 6.1:
```
Error:
PurchaseOrderHelper::#po_form_url#test_0001_should return the expected paths:
NameError: undefined local variable or method `purchase_orders_path' for #<MiniTestSpecRails::SpecTests::Test__PurchaseOrderHelper_po_form_url__test_helpers_purchase_order_helper_test_rb__4:0x0000562a7d808880>
    test/helpers/purchase_order_helper_test.rb:6:in `block (3 levels) in <main>'

Error:
PurchaseOrderHelper::#po_table_view_class#test_0001_should return the expected classes:
NoMethodError: undefined method `po_table_view_class' for #<MiniTestSpecRails::SpecTests::Test__PurchaseOrderHelper_po_table_view_class__test_helpers_purchase_order_helper_test_rb__15:0x0000562a7d7fe768>
    test/helpers/purchase_order_helper_test.rb:17:in `block (3 levels) in <main>'
```

It appears that the standard view/helper methods aren't being loaded properly. Changing to the standard minitest format has no issues:
```ruby
require 'test_helper'

class PurchaseOrderHelperTest < ActionView::TestCase
  test '#po_form_url should return the expected paths' do
    assert_equal purchase_orders_path,
        po_form_url(PurchaseOrder.new, organizations(:brewco))
    assert_equal purchase_order_path(purchase_orders(:draft).visible_id),
        po_form_url(purchase_orders(:draft), organizations(:brewco))
    assert_equal selling_purchase_order_path(purchase_orders(:draft).visible_id),
        po_form_url(purchase_orders(:draft), organizations(:bluth))
  end

  test '#po_table_view_class should return the expected classes' do
    assert_equal 'table-inner-wrapper-fh h-60', po_table_view_class([], true)
    assert_equal 'table-inner-wrapper min-h-60', po_table_view_class([], false)
    assert_equal 'table-inner-wrapper-fh max-h-60', po_table_view_class([1], true)
    assert_equal 'table-inner-wrapper', po_table_view_class([1], false)
  end
end
```
