### ISSUE TITLE
uses safe_constantize which was added in Rails 3.2

### ISSUE THREAD

**Issue by silent-e** [metaskills/minitest-spec-rails#6]
I just upgraded to v3.0.5 from v3.0.1 of this gem and my app is still using Rails 3.1.  I'm now seeing an error saying

```
NoMethodError: undefined method `safe_constantize'
```

safe_constantize was introduced in Rails 3.2 so the gemspec is incorrect now.  The gemspec says this gem works in ~ 3.0.

I'd love to see an update to get it to work per the gemspec but for now I'm downgrading back to 3.0.1

(e)
